version: "3.9"

x-default-app: &default_app
  build: .
  image: turbo_boost-streams
  tty: true
  stdin_open: true
  working_dir: /opt/turbo_boost-streams/test/dummy
  environment:
    RAILS_ENV: development
  volumes:
    - bundle:/usr/local/bundle:delegated
    - node_modules:/opt/turbo_boost-streams/node_modules

volumes:
  bundle:
  node_modules:

services:
  # ----------------------------------------------------------------------------
  # Shell - Intended for tinkering and running misc commands
  # ----------------------------------------------------------------------------
  shell:
    <<: *default_app
    container_name: turbo_boost-streams-shell
    command: /bin/bash -c "tail -f /dev/null"

  # ----------------------------------------------------------------------------
  # Web - Runs the test/dummy Rails app
  # ----------------------------------------------------------------------------
  web:
    <<: *default_app
    container_name: turbo_boost-streams-web
    ports:
      - 3000:3000
    command: >
      /bin/bash -c "git pull --no-rebase github main &&
                    cd /opt/turbo_boost-streams &&
                    bundle &&
                    yarn &&
                    cd test/dummy &&
                    rm -f tmp/pids/server.pid &&
                    bin/rails db:create db:migrate &&
                    bin/rails assets:clobber &&
                    bin/rails assets:precompile &&
                    bin/rails s --binding=0.0.0.0 --port=3000"
