version: "3.9"

x-default-app: &default_app
  build: .
  image: hopsoft/turbo_boost-streams
  tty: true
  stdin_open: true
  working_dir: /opt/turbo_boost-streams/test/dummy
  environment:
    RAILS_ENV: development
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
  networks:
    - primary
  volumes:
    - .:/opt/turbo_boost-streams
    - bundle:/usr/local/bundle
    - node_modules:/opt/turbo_boost-streams/node_modules

networks:
  primary:

volumes:
  bundle:
  node_modules:

services:
  # ==========================================================================================================
  # Shell - Intended for tinkering and running misc commands
  # ==========================================================================================================
  shell:
    <<: *default_app
    container_name: turbo_boost-streams-shell
    command: "tail -f /dev/null"

  # ==========================================================================================================
  # Web - Runs the test/dummy Rails app
  # ==========================================================================================================
  web:
    <<: *default_app
    container_name: turbo_boost-streams-web
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:3000/health"]
      interval: 30s
      timeout: 30s
      retries: 5

  # ==========================================================================================================
  # ESBuild - Runs the esbuild watcher
  # ==========================================================================================================
  esbuild:
    <<: *default_app
    container_name: turbo_boost-streams-esbuild
    command: /bin/bash -c "cd /opt/turbo_boost-streams && yarn build:watch"
    depends_on:
      web:
        condition: service_healthy

  # ==========================================================================================================
  # Tailwind - Runs the Tailwind watcher
  # ==========================================================================================================
  tailwind:
    <<: *default_app
    container_name: turbo_boost-streams-tailwind
    command: "bin/rails tailwindcss:watch"
    depends_on:
      web:
        condition: service_healthy
