name: StandardRB

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  standard:
    name: StandardRB Check Action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1']
    steps:
    - uses: actions/checkout@master
    - name: Standard
      uses: CultureHQ/actions-bundler@master
      with:
        args: install && bundle exec standardrb --format progress

